title: zzz
frequency: 1
dirfilter:
- tmp
- .git
- scripts
- vendor
- logs
ext:
- go
- js
- tmpl
enablerun: true
action:
  before:
  # - go mod init github.com/midoks/dztasks
  - go mod tidy
  - go mod vendor
  - find . -name ".DS_Store" -print -delete
  - gofmt -w ./
  - ps -ef|grep 'dztasks web'| grep -v grep | awk '{print $2}' | xargs kill -9
  after:
  - ./dztasks web &
  exit:
  - ps -ef|grep 'dztasks web'| grep -v grep | awk '{print $2}' | xargs kill -9
  # go test ./internal/tools -v 
link: https://github.com/midoks/zzz
