title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- public
- scripts
- assets
- vendor
- logs
- templates
ext:
- go
enablerun: true
action:
  before:
  # - go mod init github.com/midoks/dztasks
  - go mod tidy
  - go mod vendor
  - find . -name ".DS_Store" -print -delete
  - ps -ef|grep 'dztasks web'| grep -v grep | awk '{print $2}' | xargs kill -9
  after:
  - ./dztasks web &
  exit:
  - ps -ef|grep 'dztasks web'| grep -v grep | awk '{print $2}' | xargs kill -9
link: https://github.com/midoks/zzz
